version: '3.8'

services:
  logistic_db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./app.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - logistic_app

  logistic_api:
    container_name: logistic_api
    build: .
    ports:
      - 8000:8000
    restart: always
    volumes:
      - logistic_volumes:/usr/src/app/                # Mount the app source code
      - upload_files:/usr/src/app/uploads/          # Mount the upload folder to persist files
    depends_on:
      - logistic_db
    networks:
      - logistic_app

volumes:
  pgdata:
  logistic_volumes:
  upload_files:  # Define a volume for storing uploaded files

networks:
  logistic_app:
    driver: bridge
