version: '3.8'

services:
  app_db:
    image: postgres
    container_name: app_db
    ports:
      - "5432:5432"
    env_file:
      - ./app.dev.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  app_backend:
    container_name: app_backend
    build: .
    ports:
      - 8000:8000
    restart: always
    volumes:
      - tnt_volumes:/usr/src/app/          
      - ../tnt-uploads:/usr/src/app/tnt-uploads/
    depends_on:
      - app_db
    networks:
      - app_network
    entrypoint: ["/bin/sh", "-c", "go run migrate/migrate.go && go run main.go"]

volumes:
  pgdata:
  tnt_volumes:

networks:
  app_network:
    driver: bridge
