version: '3.8'

services:
  app_db:
    image: postgres
    container_name: app_db
    ports:
      - "5432:5432"
    env_file:
      - ./app.dev.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  app_backend:
    container_name: app_backend
    build: .
    ports:
      - 8000:8000
    restart: always
    volumes:
      - logistic_volumes:/usr/src/app/                # Mount the app source code
      - upload_files:/usr/src/app/uploads/          # Mount the upload folder to persist files
    depends_on:
      - app_db
    networks:
      - app_network
    entrypoint: ["/bin/sh", "-c", "go run migrate/migrate.go && go run main.go"]

volumes:
  pgdata:
  logistic_volumes:
  upload_files:

networks:
  app_network:
    driver: bridge
